<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>camundaFirstApp</artifactId>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <artifactId>lombok</artifactId>
              <groupId>org.projectlombok</groupId>
            </path>
          </annotationProcessorPaths>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
      </plugin>
      <plugin>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>
              <artifactId>lombok</artifactId>
              <groupId>org.projectlombok</groupId>
            </exclude>
          </excludes>
        </configuration>
        <groupId>org.springframework.boot</groupId>
      </plugin>
      <plugin>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <configuration>
          <configLocation>google_checks.xml</configLocation>
          <failOnViolation>true</failOnViolation>
          <includeTestSourceDirectory>true</includeTestSourceDirectory>
          <logViolationsToConsole>true</logViolationsToConsole>
        </configuration>
        <dependencies>
          <dependency>
            <artifactId>checkstyle</artifactId>
            <groupId>com.puppycrawl.tools</groupId>
            <version>${puppycrawl-checkstyle.version}</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
            <id>validate</id>
            <phase>compile</phase>
          </execution>
        </executions>
        <groupId>org.apache.maven.plugins</groupId>
        <version>${maven-checkstyle-plugin.version}</version>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <artifactId>spring-boot-starter-data-jdbc</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-web</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-mail</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>

    <dependency>
      <artifactId>lombok</artifactId>
      <groupId>org.projectlombok</groupId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-test</artifactId>
      <groupId>org.springframework.boot</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>h2</artifactId>
      <groupId>com.h2database</groupId>
      <scope>runtime</scope>
      <version>${h2.version}</version>
    </dependency>


    <dependency>
      <artifactId>camunda-bpm-spring-boot-starter-webapp</artifactId>
      <groupId>org.camunda.bpm.springboot</groupId>
      <version>${camunda-spring-boot.version}</version>
    </dependency>
    <dependency>
      <artifactId>commons-csv</artifactId>
      <groupId>org.apache.commons</groupId>
      <version>${commons-csv.version}</version>
    </dependency>
    <dependency>
      <artifactId>camunda-bpm-spring-boot-starter-rest</artifactId>
      <groupId>org.camunda.bpm.springboot</groupId>
      <version>${camunda-spring-boot.version}</version>
    </dependency>
    <dependency>
      <artifactId>camunda-bpm-spring-boot-starter-test</artifactId>
      <groupId>org.camunda.bpm.extension.springboot</groupId>
      <version>${camunda-bpm-spring-boot-starter-test.version}</version>
    </dependency>
    <dependency>
      <artifactId>assertj-core</artifactId>
      <groupId>org.assertj</groupId>
      <version>${assertj-core.version}</version>
    </dependency>

    <dependency>
      <artifactId>camunda-bpm-assert</artifactId>
      <groupId>org.camunda.bpm.assert</groupId>
      <version>${camunda-bpm-assert.version}</version>
    </dependency>
    <dependency>
      <artifactId>camunda-spin-dataformat-json-jackson</artifactId>
      <groupId>org.camunda.spin</groupId>
      <version>${camunda-spin.version}</version>
    </dependency>
    <dependency>
      <artifactId>camunda-spin-core</artifactId>
      <groupId>org.camunda.spin</groupId>
      <version>${camunda-spin.version}</version>
    </dependency>
    <dependency>
      <artifactId>camunda-engine-plugin-spin</artifactId>
      <groupId>org.camunda.bpm</groupId>
      <version>${camunda.version}</version>
    </dependency>
  </dependencies>
  <description>Demo project with Camunda</description>
  <groupId>ru.absolutins</groupId>
  <modelVersion>4.0.0</modelVersion>
  <name>camundaFirstApp</name>

  <parent>
    <artifactId>spring-boot-starter-parent</artifactId>
    <groupId>org.springframework.boot</groupId>
    <relativePath/>
    <version>2.7.18</version> <!-- lookup parent from repository -->
  </parent>

  <properties>
    <assertj-core.version>2.6.0</assertj-core.version>
    <camunda-bpm-assert.version>3.0.0</camunda-bpm-assert.version>
    <camunda-bpm-spring-boot-starter-test.version>2.2.0
    </camunda-bpm-spring-boot-starter-test.version>
    <camunda-spin.version>1.6.7</camunda-spin.version>
    <camunda-spring-boot.version>3.2.0</camunda-spring-boot.version>
    <camunda.version>7.10.0</camunda.version>
    <commons-csv.version>1.6</commons-csv.version>
    <h2.version>2.3.232</h2.version>
    <java.version>21</java.version>
    <maven-checkstyle-plugin.version>3.6.0</maven-checkstyle-plugin.version>
    <puppycrawl-checkstyle.version>10.20.1</puppycrawl-checkstyle.version>

  </properties>

  <version>0.0.1-SNAPSHOT</version>
</project>