server:
  port: 8080

spring:
  application:
    name: camundaFirstApp
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ${SECRET_EMAIL_LOGIN}
    password: ${SECRET_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  #          starttls:
  #            enable: true

  datasource:
    url: jdbc:h2:mem:camunda;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    generate_ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#    hibernate:
#      ddl-auto: update

camunda:
  bpm:
    job-execution:
      enabled: true
    auto-deployment-enabled: true
    application:
      scan-for-process-definitions: true
    admin-user:
      id: demo
      password: demo
      first-name: Demo
      last-name: Demo
      email: DAIP_TEST@absolutins.ru

logging:
  level:
    root: INFO
    org:
      springframework:
        boot: INFO