server:
  port: 8080

spring:
  application:
    name: camundaFirstApp
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SECRET_EMAIL_LOGIN}
    password: ${SECRET_PASSWORD}
#    host: mosrepexc02.evropolis.ru
#    port: 993
#    username: DAIP_TEST
#    password: 7NaVePuN
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:h2:mem:camunda;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    generate_ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#    hibernate:
#      ddl-auto: update

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      first-name: Demo
      last-name: Demo
      email: DAIP_TEST@absolutins.ru

logging:
  level:
    root: INFO
    org:
      springframework:
        boot: DEBUG